# Generated by Django 2.2.6 on 2022-02-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantgeoposition',
            name='name',
        ),
    ]
