# Generated by Django 2.2.6 on 2021-12-08 08:40

from django.db import migrations


def fix_price(apps, schema_editor):
    Product = apps.get_model('foodcartapp', 'Product')
    OrderDetails = apps.get_model('foodcartapp', 'OrderDetails')
    products = Product.objects.all()
    for product in products:
        orderdetails = OrderDetails.objects.filter(product=product)
        for orderdetail in orderdetails:
            orderdetail.fixed_price = product.price
            orderdetail.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0039_auto_20211208_1106'),
    ]

    operations = [
        migrations.RunPython(fix_price)
    ]
