# Generated by Django 2.2.6 on 2021-12-08 08:40

from django.db import migrations


def fix_price(apps, schema_editor):
    OrderDetails = apps.get_model('foodcartapp', 'OrderDetails')
    order_details = OrderDetails.objects.select_related('product').filter(fixed_price=None)
    for order_detail in order_details.iterator():
        order_detail.fixed_price = order_detail.product.price
        order_detail.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0039_auto_20211208_1106'),
    ]

    operations = [
        migrations.RunPython(fix_price)
    ]
