# Generated by Django 2.2.6 on 2021-12-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('processed_order', 'обработанный'), ('unprocessed_order', 'необработанный')], default='unprocessed_order', max_length=20, verbose_name='статус'),
        ),
    ]
