# Generated by Django 2.2.6 on 2021-12-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('processed_order', 'обработанный'), ('unprocessed_order', 'необработанный')], db_index=True, default='unprocessed_order', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'наличностью'), ('creditcard', 'электронно')], db_index=True, default='creditcard', max_length=20, verbose_name='способ оплаты'),
        ),
    ]
