# Generated by Django 2.2.6 on 2021-12-10 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20211209_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantGeoPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запроса к геокодеру')),
            ],
            options={
                'verbose_name': 'геопозиция ресторана',
                'verbose_name_plural': 'геопозиция ресторанов',
            },
        ),
    ]
