# Generated by Django 3.2 on 2022-01-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20220103_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='payment_method',
        ),
    ]
