# Generated by Django 3.2 on 2022-01-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_rename_payment_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('unspecified', 'не указано'), ('cash', 'наличностью'), ('creditcard', 'электронно')], db_index=True, default='unspecified', max_length=20, verbose_name='способ оплаты'),
        ),
    ]
