# Generated by Django 3.2 on 2022-01-03 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='фиксированная цена'),
        ),
    ]
