# Generated by Django 2.2.6 on 2022-02-03 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_auto_20220123_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.FloatField(default=None, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='order',
            name='lon',
            field=models.FloatField(default=None, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='фиксированная цена'),
        ),
    ]
