# Generated by Django 2.2.6 on 2022-02-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_auto_20220204_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lon',
            field=models.FloatField(null=True, verbose_name='долгота'),
        ),
    ]
