# Generated by Django 2.2.6 on 2022-02-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_auto_20220204_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='долгота'),
        ),
    ]
